#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-ubuntu}"
export DISABLE_RTKIT="y"
export PIPEWIRE_LATENCY="128/48000"
until [ -S "${XDG_RUNTIME_DIR}/pipewire-0" ] || [ -n "$(ls ${XDG_RUNTIME_DIR}/pipewire-*.lock 2>/dev/null)" ]; do sleep 0.5; done
exec dbus-run-session -- /usr/bin/wireplumber
