version: "3.9"
services:
  dist:
    image: selkies-gstreamer-py-build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYPI_PACKAGE: selkies-gstreamer
        PACKAGE_VERSION: 1.0.0-dev
  web:
    image: gst-web
    build:
      context: ./addons/gst-web
      dockerfile: Dockerfile
  test:
    image: selkies-gstreamer-example:latest-ubuntu20.04
    # Uncomment below to use Ubuntu 18.04 image.
    #image: selkies-gstreamer-example:latest-ubuntu18.04
    entrypoint: ["/tini", "--", "/bin/bash"]
    build:
      context: .
      dockerfile: Dockerfile.example
      args:
        UBUNTU_RELEASE: 20.04
        # Uncomment below id using Ubuntu 18.04 image.
        #UBUNTU_RELEASE: 18.04

        # Testing with gstreamer build in-repo:
        # 1. (cd addons/gstreamer && docker build -t gstreamer:latest-ubuntu20.04 .)
        # 2. export GSTREAMER_BASE_IMAGE=gstreamer
        # 3. docker-compose build test
        GSTREAMER_BASE_IMAGE: ${GSTREAMER_BASE_IMAGE:-ghcr.io/selkies-project/selkies-gstreamer/gstreamer}
        GSTREAMER_BASE_IMAGE_RELEASE: latest

        PY_BUILD_IMAGE: selkies-gstreamer-py-build:latest
        WEB_IMAGE: gst-web:latest
        PYPI_PACKAGE: selkies_gstreamer
        PACKAGE_VERSION: 1.0.0.dev0
    environment:
      # Basic authentication
      ENABLE_BASIC_AUTH: ${ENABLE_BASIC_AUTH}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}

      # TURN with shared secret or user/pass
      TURN_SHARED_SECRET: ${TURN_SHARED_SECRET}
      TURN_HOST: ${TURN_HOST}
      TURN_PORT: ${TURN_PORT}
      TURN_USERNAME: ${TURN_USERNAME}
      TURN_PASSWORD: ${TURN_PASSWORD}

      # Turn with coTURN web
      COTURN_WEB_URI: ${COTURN_WEB_URI}
      COTURN_WEB_USERNAME: ${COTURN_WEB_USERNAME}
      COTURN_AUTH_HEADER_NAME: ${COTURN_AUTH_HEADER_NAME}

      # Additional server-side settings.
      WEBRTC_ENABLE_RESIZE: ${WEBRTC_ENABLE_RESIZE}

      # DEBUG remote cursors
      DEBUG_CURSORS: ${DEBUG_CURSORS:-false}
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src/selkies_gstreamer
        target: /usr/local/lib/python3.8/dist-packages/selkies_gstreamer
        read_only: true

    # Configure for interactive session
    stdin_open: true
    tty: true

