version: "3.9"
services:
  dist:
    image: selkies-gstreamer-py-build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYPI_PACKAGE: selkies-gstreamer-disla
        PACKAGE_VERSION: 1.0.0-rc0
  web:
    image: gst-web
    build:
      context: ./addons/gst-web
      dockerfile: Dockerfile
  test:
    image: selkies-gstreamer-example
    entrypoint: ["/tini", "--", "/bin/bash"]
    build:
      context: .
      dockerfile: Dockerfile.example
      args:
        GSTREAMER_IMAGE: ghcr.io/selkies-project/selkies-gstreamer/gstreamer:latest
        PY_BUILD_IMAGE: selkies-gstreamer-py-build:latest
        WEB_IMAGE: gst-web:latest
        PYPI_PACKAGE: selkies_gstreamer_disla
        BUILD_VERSION: 1.0.0rc0
    environment:
      TURN_SHARED_SECRET: ${TURN_SHARED_SECRET}
      TURN_HOST: ${TURN_HOST}
      TURN_PORT: ${TURN_PORT}
      COTURN_AUTH_HEADER_NAME: ${COTURN_AUTH_HEADER_NAME}
      WEBRTC_ENABLE_RESIZE: ${WEBRTC_ENABLE_RESIZE}
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src/selkies_gstreamer
        target: /usr/local/lib/python3.8/dist-packages/selkies_gstreamer
        read_only: true

    # Configure for interactive session
    stdin_open: true
    tty: true

