#!/bin/bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-ubuntu}"
export DISABLE_RTKIT="y"
export PIPEWIRE_LATENCY="${PIPEWIRE_LATENCY:-256/48000}"
until [ -d "${XDG_RUNTIME_DIR}" ]; do sleep 0.5; done
exec dbus-run-session -- /usr/bin/pipewire
