// Postbuild: ship the gamepad remap DB (generated by selkies-web-core's own
// postbuild gendb.js) into this dashboard's dist. Generated at build time so
// the 1200+ JSON files never live in the repo.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, '../selkies-web-core/dist/jsdb');
const dst = path.resolve(here, 'dist/jsdb');

if (!fs.existsSync(src)) {
  console.warn(
    `WARNING: ${src} missing — build selkies-web-core first. ` +
    'Gamepad remap lookups (jsdb/*.json) will 404 and pads fall back to browser-default mappings.'
  );
  process.exit(0);
}
fs.rmSync(dst, { recursive: true, force: true });
fs.cpSync(src, dst, { recursive: true });
console.log(`jsdb: ${fs.readdirSync(dst).length} mapping files copied into dist/`);
