# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: coturn
spec:
  selector:
    asm: ingressgateway-xlb
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      # Default gateway handles all hosts
      hosts:
        - "*"