kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: coturn

secretGenerator:
- name: turn-shared-secret
  files:
  - TURN_SHARED_SECRET
  - TURN_REALM
  - TURN_EXTERNAL_IP

resources:
  - namespace.yaml
  - coturn-deploy.yaml
  - coturn-discovery-service.yaml
  - coturn-gateway.yaml
  - coturn-hpa.yaml
  - coturn-lb-service.yaml
  - coturn-service.yaml
  - coturn-web-rbac.yaml
  - coturn-web-deploy.yaml
  - coturn-web-service.yaml
  - coturn-web-virtualservice.yaml

images:
  - name: ghcr.io/selkies-project/selkies-gstreamer/coturn
    newName: ghcr.io/selkies-project/selkies-gstreamer/coturn
    newTag: latest
  - name: ghcr.io/selkies-project/selkies-gstreamer/coturn-web
    newName: ghcr.io/selkies-project/selkies-gstreamer/coturn-web
    newTag: latest