apiVersion: v1
kind: Service
metadata:
  name: selkies-gstreamer
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: http-web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: selkies-gstreamer
