# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

timeout: 7200s
substitutions:
  _ACTION: apply
  _NAME: selkies
  _REGION: us-west1
  _TURN_REALM:
tags:
  - selkies-infra-turn-vm
  - selkies-setup
steps:
  ###
  # Apply terraform to create cluster
  ###
  - name: ghcr.io/selkies-project/selkies-gstreamer/infra-gcp-installer:latest
    id: "terraform-apply"
    env:
      - TF_VAR_project_id=${PROJECT_ID}
      - TF_VAR_name=${_NAME}
      - TF_VAR_region=${_REGION}
      - TF_VAR_turn_realm=${_TURN_REALM}
      - TERRAFORM_WORKSPACE_NAME=turn-vm-${_REGION}
      - ACTION=${_ACTION}
