#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Render docs/settings.md from the setting definitions in settings.py.

The settings module is read statically (the definition list is a literal), so
this needs no Selkies dependencies and nothing the environment holds can leak
into the page. Run from anywhere:

    python3 scripts/generate-settings-doc.py          # rewrite docs/settings.md
    python3 scripts/generate-settings-doc.py --check  # exit 1 if it is stale
"""

import argparse
import ast
import os
import sys
from typing import Any, Dict, List, Optional, Set

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_PY = os.path.join(REPO, "src", "selkies", "settings.py")
OUTPUT = os.path.join(REPO, "docs", "settings.md")

HEADER = """\
---
title: Settings Reference
description: Every command-line option and environment variable of the selkies server, with its type and default.
---

<!-- Generated by scripts/generate-settings-doc.py from src/selkies/settings.py. Edit the definitions there and rerun the script; do not edit this page by hand. -->

Every setting below is one entry of `SETTING_DEFINITIONS` in [`src/selkies/settings.py`](https://github.com/selkies-project/selkies/tree/main/src/selkies/settings.py), which is also what `selkies --help` prints. Each one is read with the precedence **command-line flag** > **`SELKIES_<NAME>` environment variable** > **fallback environment variable** (where one is listed) > **built-in default**. The flag accepts both spellings, `--my-setting` and `--my_setting`, and a bool flag takes a value (`--enable-resize=false`). A flag or variable set to an empty value means the built-in default; an unknown flag is ignored with a warning, never an error.

{syntax}
"""

TABLE_HEAD = """\
## Settings

| Setting | Environment | Type | Default | Description |
| --- | --- | --- | --- | --- |
"""


def load_definitions() -> Dict[str, Any]:
    """Return the definition list and the sensitive-name set, read statically."""
    with open(SETTINGS_PY, encoding="utf-8") as f:
        source = f.read()
    tree = ast.parse(source, SETTINGS_PY)
    definitions: Optional[List[Dict[str, Any]]] = None
    sensitive: Set[str] = set()
    for node in tree.body:
        target = None
        if isinstance(node, ast.AnnAssign):
            target = node.target
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
        name = getattr(target, "id", None)
        if name == "SETTING_DEFINITIONS" and node.value is not None:
            definitions = ast.literal_eval(node.value)
        elif name == "SENSITIVE_SETTING_NAMES" and node.value is not None:
            value = node.value
            if isinstance(value, ast.Call) and value.args:
                value = value.args[0]
            sensitive = set(ast.literal_eval(value))
    if definitions is None:
        raise SystemExit(f"SETTING_DEFINITIONS not found in {SETTINGS_PY}")
    return {"definitions": definitions, "sensitive": sensitive, "docstring": ast.get_docstring(tree) or ""}


def syntax_section(docstring: str) -> str:
    """The value-syntax part of the settings module docstring, as a section."""
    marker = "Override value syntax"
    start = docstring.find(marker)
    if start < 0:
        return ""
    body = docstring[start:].strip()
    _, _, bullets = body.partition("\n")
    return "## Value syntax\n\n" + bullets.strip() + "\n"


def cell(text: str) -> str:
    """Escape a table cell: pipes end cells and newlines end rows."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def code(text: Any) -> str:
    return "`" + cell(text) + "`"


def env_cell(setting: Dict[str, Any]) -> str:
    names = [f"SELKIES_{setting['name'].upper()}"]
    fallback = setting.get("env_var")
    for name in [fallback] if isinstance(fallback, str) else (fallback or []):
        if name not in names:
            names.append(name)
    return ", ".join(code(n) for n in names)


def span(setting: Dict[str, Any]) -> str:
    """An int/float bound annotation such as ` 1 to 65535`, empty when unbounded."""
    low, high = setting.get("min"), setting.get("max")
    if low is None and high is None:
        return ""
    if low is None:
        return f" up to {high}"
    if high is None:
        return f" from {low}"
    return f" {low} to {high}"


def type_cell(setting: Dict[str, Any]) -> str:
    stype = setting["type"]
    meta = setting.get("meta", {})
    if stype in ("int", "float"):
        bounds = span(setting)
        return f"{stype},{bounds}" if bounds else stype
    if stype == "range":
        return f"range, within {code(setting['default'])}"
    if stype in ("enum", "list"):
        choices = ", ".join(code(c) for c in meta.get("allowed", []))
        label = "one of" if stype == "enum" else "any of"
        text = f"{stype}: {label} {choices}" if choices else stype
        value_range = meta.get("value_range")
        if value_range:
            text += f", or any value from {value_range[0]} to {value_range[1]}"
        return text
    return stype


def default_cell(setting: Dict[str, Any]) -> str:
    stype = setting["type"]
    if stype == "bool":
        return code("true" if setting["default"] else "false")
    if stype == "range":
        return code(setting.get("meta", {}).get("default_value", ""))
    default = setting["default"]
    if default == "" or default is None:
        return "(empty)"
    return code(default)


def description_cell(setting: Dict[str, Any], sensitive: Set[str]) -> str:
    text = cell(setting["help"])
    if setting["name"] in sensitive:
        text += " Never sent to clients."
    return text


def render() -> str:
    loaded = load_definitions()
    lines = [HEADER.format(syntax=syntax_section(loaded["docstring"])), TABLE_HEAD]
    for setting in loaded["definitions"]:
        flag = code("--" + setting["name"].replace("_", "-"))
        lines.append(
            f"| {flag} | {env_cell(setting)} | {cell(type_cell(setting))} | "
            f"{default_cell(setting)} | {description_cell(setting, loaded['sensitive'])} |\n"
        )
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 when docs/settings.md is out of date instead of rewriting it")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            with open(OUTPUT, encoding="utf-8") as f:
                current = f.read()
        except OSError:
            current = ""
        if current != rendered:
            print(f"{os.path.relpath(OUTPUT, REPO)} is out of date; run {os.path.relpath(__file__, REPO)}", file=sys.stderr)
            return 1
        print(f"{os.path.relpath(OUTPUT, REPO)} is up to date")
        return 0
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(rendered)
    rows = sum(1 for line in rendered.splitlines() if line.startswith("| `--"))
    print(f"wrote {os.path.relpath(OUTPUT, REPO)} ({rows} settings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
