#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""Render docs/settings.md from the setting definitions in settings.py.

The settings module is read statically (the definition list is a literal), so
this needs no Selkies dependencies and nothing the environment holds can leak
into the page. Run from anywhere:

    python3 scripts/generate-settings-doc.py          # rewrite docs/settings.md
    python3 scripts/generate-settings-doc.py --check  # exit 1 if it is stale
"""

import argparse
import ast
import os
import sys
from typing import Any, Dict, List, Optional, Set

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_PY = os.path.join(REPO, "src", "selkies", "settings.py")
OUTPUT = os.path.join(REPO, "docs", "settings.md")

HEADER = """\
---
title: Settings Reference
description: Every command-line option and environment variable of the selkies server, with its type and default.
full: true
---

<!-- Generated by scripts/generate-settings-doc.py from src/selkies/settings.py. Edit the definitions there and rerun the script; do not edit this page by hand. -->

Every setting below is one entry of `SETTING_DEFINITIONS` in [`src/selkies/settings.py`](https://github.com/selkies-project/selkies/tree/main/src/selkies/settings.py), which is also what `selkies --help` prints. Each one is read with the precedence **command-line flag** > **`SELKIES_<NAME>` environment variable** > **fallback environment variable** (where one is listed) > **built-in default**. The flag accepts both spellings, `--my-setting` and `--my_setting`, and a bool flag takes a value (`--enable-resize=false`) or stands alone for true (`--public`). A flag or variable set to an empty value means the built-in default; an unknown flag is ignored with a warning, never an error.

The settings are grouped by what they govern, the ones a deployment reaches for first at the top of each group. The stream settings are the client's to choose from the dashboard, and a deployment sets them only to narrow the menu or to lock a single value; see [Usage](usage.md#command-line-options-and-environment-variables) for how a locked value reads.

{syntax}
"""

# Every setting is placed in one section, ordered by what a deployment
# reaches for first; a setting missing here fails the generation, so a new
# one is placed on purpose rather than appended to the end of the page.
SECTIONS = [
    ("Stream", "The video encoder and its rate control. The dashboard chooses among what the server allows.", [
        "encoder", "video_fullcolor", "framerate", "video_bitrate", "video_crf", "rate_control_mode",
        "enable_rate_control", "congestion_control", "keyframe_interval", "video_min_qp", "video_max_qp",
        "jpeg_quality", "video_streaming_mode", "use_paint_over_quality", "paint_over_jpeg_quality",
        "video_paintover_crf", "video_paintover_burst_frames", "use_cpu", "gpu_id", "encode_dri",
        "webrtc_pacer", "backpressure_queue_size",
    ]),
    ("Audio", "Server-to-client audio and the microphone uplink.", [
        "audio_enabled", "audio_bitrate", "audio_channels", "audio_device_name", "audio_frame_duration_ms",
        "audio_redundancy", "audio_redundancy_distance", "microphone_enabled",
    ]),
    ("Display", "Resolution, scaling, cursors, and the second display.", [
        "enable_resize", "manual_resolution", "manual_width", "manual_height", "force_aligned_resolution",
        "scaling_dpi", "use_css_scaling", "second_screen", "enable_cursors", "cursor_size",
        "use_browser_cursors", "raw_pointer_motion", "watermark_path", "watermark_location", "debug_cursors",
    ]),
    ("Backends", "The X11 or Wayland capture backend and the GPU it renders on.", [
        "wayland", "render_dri", "auto_gpu", "app_wayland_display", "wayland_host_display",
        "wayland_socket_index", "computer_use_bind", "computer_use_token",
    ]),
    ("Session start", "What a session starts with, and hooks around its first and last client.", [
        "video_on_start", "audio_on_start", "microphone_on_start", "webcam_on_start", "gamepad_on_start",
        "app_wait_ready", "app_ready_file", "run_after_connect", "run_after_disconnect",
    ]),
    ("Input", "Gamepads, keyboard chords, and the input devices published to the session.", [
        "gamepad_enabled", "uinput_gamepad", "js_socket_path", "uinput_mouse_socket", "publish_input_devices",
        "keyboard_shortcuts", "mac_cmd_as_ctrl",
    ]),
    ("Clipboard, files, and printing", "What leaves and enters the session besides the stream.", [
        "enable_clipboard", "enable_binary_clipboard", "clipboard_seamless", "file_transfers",
        "file_manager_path", "file_transfer_limit_mbps", "printing_enabled", "print_spool_path",
    ]),
    ("Webcam", "The camera uplink and the virtual V4L2 device it is published as.", [
        "webcam_enabled", "webcam_encoder", "webcam_width", "webcam_height", "webcam_pixel_format",
        "webcam_device", "webcam_socket_path",
    ]),
    ("Sharing", "Viewer and player links for a session without provisioned tokens.", [
        "enable_sharing", "enable_shared", "enable_collab", "enable_player2", "enable_player3", "enable_player4",
    ]),
    ("Client interface", "What the shipped web interface shows; the feature behind a hidden control keeps working.", [
        "ui_title", "ui_show_logo", "ui_show_sidebar", "ui_show_core_buttons", "ui_sidebar_show_video_settings",
        "ui_sidebar_show_screen_settings", "ui_sidebar_show_audio_settings", "ui_sidebar_show_stats",
        "ui_sidebar_show_shortcuts", "ui_sidebar_show_clipboard", "ui_sidebar_show_files", "ui_sidebar_show_apps",
        "ui_sidebar_show_sharing", "ui_sidebar_show_gamepads", "ui_sidebar_show_webcam",
        "ui_sidebar_show_fullscreen", "ui_sidebar_show_gaming_mode", "ui_sidebar_show_trackpad",
        "ui_sidebar_show_keyboard_button", "ui_sidebar_show_soft_buttons",
    ]),
    ("Server", "The transport, the listening address, TLS, the login, and the master token.", [
        "mode", "enable_dual_mode", "addr", "public", "port", "unix_socket", "subfolder", "web_root",
        "allowed_origins", "enable_https", "https_cert", "https_key", "cert_reload_interval",
        "enable_basic_auth", "basic_auth_user", "basic_auth_password", "basic_auth_viewonly_password",
        "master_token", "command_enabled", "debug",
    ]),
    ("WebRTC and TURN", "The opt-in WebRTC transport's ICE, STUN, and TURN configuration.", [
        "rtc_config_json", "turn_host", "turn_port", "turn_protocol", "turn_tls", "turn_shared_secret",
        "turn_username", "turn_password", "turn_rest_uri", "turn_rest_api_key", "turn_rest_username",
        "turn_rest_username_auth_header", "turn_rest_protocol_header", "turn_rest_tls_header", "stun_host",
        "stun_port", "enable_cloudflare_turn", "cloudflare_turn_token_id", "cloudflare_turn_api_token",
        "webrtc_public_ip", "webrtc_port_range", "webrtc_udp_mux_port", "webrtc_tcp_mux_port", "webrtc_ice_lite",
    ]),
    ("Recording, audit, and metrics", "The recording tap, the audit webhook, and the metrics endpoints.", [
        "recording_socket", "audit_webhook_url", "audit_webhook_token", "audit_webhook_timeout",
        "enable_metrics_http", "enable_webrtc_statistics", "webrtc_statistics_dir",
    ]),
]

TABLE_HEAD = """\
| Setting | Default | Description |
| --- | --- | --- |
"""


def load_definitions() -> Dict[str, Any]:
    """Return the definition list and the sensitive-name set, read statically."""
    with open(SETTINGS_PY, encoding="utf-8") as f:
        source = f.read()
    tree = ast.parse(source, SETTINGS_PY)
    definitions: Optional[List[Dict[str, Any]]] = None
    sensitive: Set[str] = set()
    for node in tree.body:
        target = None
        if isinstance(node, ast.AnnAssign):
            target = node.target
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
        name = getattr(target, "id", None)
        if name == "SETTING_DEFINITIONS" and node.value is not None:
            definitions = ast.literal_eval(node.value)
        elif name == "SENSITIVE_SETTING_NAMES" and node.value is not None:
            value = node.value
            if isinstance(value, ast.Call) and value.args:
                value = value.args[0]
            sensitive = set(ast.literal_eval(value))
    if definitions is None:
        raise SystemExit(f"SETTING_DEFINITIONS not found in {SETTINGS_PY}")
    return {"definitions": definitions, "sensitive": sensitive, "docstring": ast.get_docstring(tree) or ""}


def syntax_section(docstring: str) -> str:
    """The value-syntax part of the settings module docstring, as a section."""
    marker = "Override value syntax"
    start = docstring.find(marker)
    if start < 0:
        return ""
    body = docstring[start:].strip()
    _, _, bullets = body.partition("\n")
    return "## Value syntax\n\n" + bullets.strip() + "\n"


def cell(text: str) -> str:
    """Escape a table cell: pipes end cells and newlines end rows."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def code(text: Any) -> str:
    return "`" + cell(text) + "`"


def env_cell(setting: Dict[str, Any]) -> str:
    names = [f"SELKIES_{setting['name'].upper()}"]
    fallback = setting.get("env_var")
    for name in [fallback] if isinstance(fallback, str) else (fallback or []):
        if name not in names:
            names.append(name)
    return ", ".join(code(n) for n in names)


def span(setting: Dict[str, Any]) -> str:
    """An int/float bound annotation such as ` 1 to 65535`, empty when unbounded."""
    low, high = setting.get("min"), setting.get("max")
    if low is None and high is None:
        return ""
    if low is None:
        return f" up to {high}"
    if high is None:
        return f" from {low}"
    return f" {low} to {high}"


def type_cell(setting: Dict[str, Any]) -> str:
    stype = setting["type"]
    meta = setting.get("meta", {})
    if stype in ("int", "float"):
        bounds = span(setting)
        return f"{stype},{bounds}" if bounds else stype
    if stype == "range":
        return f"range, within {code(setting['default'])}"
    if stype in ("enum", "list"):
        choices = ", ".join(code(c) for c in meta.get("allowed", []))
        label = "one of" if stype == "enum" else "any of"
        text = f"{stype}: {label} {choices}" if choices else stype
        value_range = meta.get("value_range")
        if value_range:
            text += f", or any value from {value_range[0]} to {value_range[1]}"
        return text
    return stype


def default_cell(setting: Dict[str, Any]) -> str:
    stype = setting["type"]
    if stype == "bool":
        return code("true" if setting["default"] else "false")
    if stype == "range":
        return code(setting.get("meta", {}).get("default_value", ""))
    default = setting["default"]
    if default == "" or default is None:
        return "(empty)"
    return code(default)


def description_cell(setting: Dict[str, Any], sensitive: Set[str]) -> str:
    text = cell(setting["help"])
    if setting["name"] in sensitive:
        text += " Never sent to clients."
    return text


def row(setting: Dict[str, Any], sensitive: Set[str]) -> str:
    flag = code("--" + setting["name"].replace("_", "-"))
    return (
        f"| {flag}<br>{env_cell(setting).replace(', ', '<br>')} | "
        f"{default_cell(setting)}<br>{cell(type_cell(setting))} | "
        f"{description_cell(setting, sensitive)} |\n"
    )


def render() -> str:
    loaded = load_definitions()
    by_name = {setting["name"]: setting for setting in loaded["definitions"]}
    placed = [name for _, _, names in SECTIONS for name in names]
    unknown = sorted(set(placed) - set(by_name))
    missing = [name for name in by_name if name not in placed]
    duplicates = sorted({name for name in placed if placed.count(name) > 1})
    if unknown or missing or duplicates:
        raise SystemExit(
            f"SECTIONS names settings that do not exist: {unknown}; leaves out: {missing}; repeats: {duplicates}")
    lines = [HEADER.format(syntax=syntax_section(loaded["docstring"]))]
    for title, lead, names in SECTIONS:
        lines.append(f"## {title}\n\n{lead}\n\n{TABLE_HEAD}")
        lines.extend(row(by_name[name], loaded["sensitive"]) for name in names)
        lines.append("\n")
    return "".join(lines).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 when docs/settings.md is out of date instead of rewriting it")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            with open(OUTPUT, encoding="utf-8") as f:
                current = f.read()
        except OSError:
            current = ""
        if current != rendered:
            print(f"{os.path.relpath(OUTPUT, REPO)} is out of date; run {os.path.relpath(__file__, REPO)}", file=sys.stderr)
            return 1
        print(f"{os.path.relpath(OUTPUT, REPO)} is up to date")
        return 0
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(rendered)
    rows = sum(1 for line in rendered.splitlines() if line.startswith("| `--"))
    print(f"wrote {os.path.relpath(OUTPUT, REPO)} ({rows} settings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
