// Postbuild: ship the gamepad remap DB (generated by selkies-web-core's own
// postbuild gendb.js) into this dashboard's dist. Generated at build time so
// the per-platform JSON files never live in the repo.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, '../selkies-web-core/dist/jsdb');
const dst = path.resolve(here, 'dist/jsdb');

if (!fs.existsSync(src)) {
  console.warn(
    `WARNING: ${src} missing — build selkies-web-core first. ` +
    'Gamepad remap lookups (jsdb/<platform>/*.json) will 404 and pads fall back to browser-default mappings.'
  );
  process.exit(0);
}
fs.rmSync(dst, { recursive: true, force: true });
fs.cpSync(src, dst, { recursive: true });
const mappingCount = fs
  .readdirSync(dst, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .reduce((total, entry) => total + fs.readdirSync(path.join(dst, entry.name)).length, 0);
console.log(`jsdb: ${mappingCount} mapping files copied into dist/`);
