# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Publish release

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  get_semver:
    name: Get Semantic Version
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.get.outputs.semver }}
    steps:
    - id: get
      env:
        RELEASE_VERSION: ${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
      run: |
        if [[ "${RELEASE_VERSION}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
          echo "semver=${RELEASE_VERSION/v/}" >> "$GITHUB_OUTPUT"
        else
          # If ref name does not match semver, default to 0.0.0.
          # This happens when running from a branch such as main.
          echo "semver=0.0.0" >> "$GITHUB_OUTPUT"
        fi

  # Note: When modifying this job, copy modifications to all other workflow image jobs
  component_images:
    needs: get_semver
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: coturn
          context: addons/coturn
          platforms: linux/amd64,linux/arm64

        - name: coturn-web
          context: addons/coturn-web
          platforms: linux/amd64,linux/arm64

        - name: gst-web
          context: addons/gst-web

        - name: gstreamer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
          context: addons/gstreamer

        - name: gstreamer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
          context: addons/gstreamer

        - name: gstreamer
          version_suffix: -ubuntu24.04
          build_args: |
            DISTRIB_RELEASE=24.04
          context: addons/gstreamer

        - name: js-interposer
          version_suffix: -ubuntu20.04
          build_args: |
            DISTRIB_RELEASE=20.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=${{ needs.get_semver.outputs.semver }}
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg
          platforms: linux/amd64,linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu22.04
          build_args: |
            DISTRIB_RELEASE=22.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=${{ needs.get_semver.outputs.semver }}
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg
          platforms: linux/amd64,linux/arm64

        - name: js-interposer
          version_suffix: -ubuntu24.04
          build_args: |
            DISTRIB_RELEASE=24.04
            PKG_NAME=selkies-js-interposer
            PKG_VERSION=${{ needs.get_semver.outputs.semver }}
          context: addons/js-interposer
          dockerfile: Dockerfile.ubuntu_debpkg
          platforms: linux/amd64,linux/arm64

        - name: turn-rest
          context: addons/turn-rest
          platforms: linux/amd64,linux/arm64

        - name: infra-gcp-installer
          context: infra/gce/installer-image
          diff: infra/gce

        - name: py-build
          build_args: |
            PACKAGE_VERSION=${{ needs.get_semver.outputs.semver }}
          context: .

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
    - uses: actions/checkout@v4

    - name: Build & publish ${{ matrix.name }} image
      uses: ./.github/actions/build_and_publish_image
      with:
        build_args: ${{ matrix.build_args }}
        context: ${{ matrix.context }}
        dockerfile: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        subproject: ${{ matrix.name }}
        tags: |
          ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}${{ matrix.version_suffix }}
          ghcr.io/${{ github.repository }}/${{ matrix.name }}:latest${{ matrix.version_suffix }}

  # Note: When modifying this job, copy modifications to all other workflow image jobs
  example_images:
    needs:
    - get_semver
    - component_images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: gst-py-example
          version_suffix: -ubuntu20.04
          build_args: |
            PACKAGE_VERSION=${{ needs.get_semver.outputs.semver }}
            DISTRIB_RELEASE=20.04
            GSTREAMER_BASE_IMAGE_RELEASE=${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            PY_BUILD_IMAGE=ghcr.io/${{ github.repository }}/py-build:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            WEB_IMAGE=ghcr.io/${{ github.repository }}/gst-web:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            JS_BASE_IMAGE_RELEASE=${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            JS_BASE_IMAGE=ghcr.io/${{ github.repository }}/js-interposer
          context: addons/example

        - name: gst-py-example
          version_suffix: -ubuntu22.04
          build_args: |
            PACKAGE_VERSION=${{ needs.get_semver.outputs.semver }}
            DISTRIB_RELEASE=22.04
            GSTREAMER_BASE_IMAGE_RELEASE=${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            PY_BUILD_IMAGE=ghcr.io/${{ github.repository }}/py-build:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            WEB_IMAGE=ghcr.io/${{ github.repository }}/gst-web:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            JS_BASE_IMAGE_RELEASE=${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            JS_BASE_IMAGE=ghcr.io/${{ github.repository }}/js-interposer
          context: addons/example

        - name: gst-py-example
          version_suffix: -ubuntu24.04
          build_args: |
            PACKAGE_VERSION=${{ needs.get_semver.outputs.semver }}
            DISTRIB_RELEASE=24.04
            GSTREAMER_BASE_IMAGE_RELEASE=${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            PY_BUILD_IMAGE=ghcr.io/${{ github.repository }}/py-build:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            WEB_IMAGE=ghcr.io/${{ github.repository }}/gst-web:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            JS_BASE_IMAGE_RELEASE=${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}
            JS_BASE_IMAGE=ghcr.io/${{ github.repository }}/js-interposer
          context: addons/example

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
    - uses: actions/checkout@v4

    - name: Build & publish ${{ matrix.name }} image
      uses: ./.github/actions/build_and_publish_image
      with:
        build_args: ${{ matrix.build_args }}
        context: ${{ matrix.context }}
        dockerfile: ${{ matrix.dockerfile }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        subproject: ${{ matrix.name }}
        tags: |
          ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}${{ matrix.version_suffix }}
          ghcr.io/${{ github.repository }}/${{ matrix.name }}:latest${{ matrix.version_suffix }}

  create_release:
    needs:
    - get_semver
    - component_images
    - example_images
    runs-on: ubuntu-latest
    name: Create ${{ github.ref }} draft release
    steps:
    - uses: softprops/action-gh-release@v2
      with:
        name: "Release ${{ github.ref }}"
        tag_name: ${{ github.ref }}
        body: "**By downloading the GStreamer build files, you acknowledge and agree to the terms of libraries and executables licensed GPLv2, GPLv3 or https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvrtc/LICENSE.txt.**"
        draft: true
        generate_release_notes: true

  upload_artifacts:
    needs:
    - get_semver
    - component_images
    - example_images
    - create_release
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    env:
      TEMP_DIR: /tmp
    strategy:
      matrix:
        include:
        - name: gstreamer
          version_suffix: -ubuntu20.04
          source: /opt/selkies-gstreamer-latest.tar.gz
          target: gstreamer-selkies_gpl_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu20.04_amd64.tar.gz

        - name: gstreamer
          version_suffix: -ubuntu22.04
          source: /opt/selkies-gstreamer-latest.tar.gz
          target: gstreamer-selkies_gpl_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu22.04_amd64.tar.gz

        - name: gstreamer
          version_suffix: -ubuntu24.04
          source: /opt/selkies-gstreamer-latest.tar.gz
          target: gstreamer-selkies_gpl_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu24.04_amd64.tar.gz

        - name: js-interposer
          version_suffix: -ubuntu20.04
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.deb
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu20.04_amd64.deb

        - name: js-interposer
          version_suffix: -ubuntu22.04
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.deb
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu22.04_amd64.deb

        - name: js-interposer
          version_suffix: -ubuntu24.04
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.deb
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu24.04_amd64.deb

        - name: js-interposer
          version_suffix: -ubuntu20.04
          platforms: linux/arm64
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.deb
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu20.04_arm64.deb

        - name: js-interposer
          version_suffix: -ubuntu22.04
          platforms: linux/arm64
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.deb
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu22.04_arm64.deb

        - name: js-interposer
          version_suffix: -ubuntu24.04
          platforms: linux/arm64
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.deb
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu24.04_arm64.deb

        - name: js-interposer
          version_suffix: -ubuntu20.04
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.tar.gz
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu20.04_amd64.tar.gz

        - name: js-interposer
          version_suffix: -ubuntu22.04
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.tar.gz
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu22.04_amd64.tar.gz

        - name: js-interposer
          version_suffix: -ubuntu24.04
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.tar.gz
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu24.04_amd64.tar.gz

        - name: js-interposer
          version_suffix: -ubuntu20.04
          platforms: linux/arm64
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.tar.gz
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu20.04_arm64.tar.gz

        - name: js-interposer
          version_suffix: -ubuntu22.04
          platforms: linux/arm64
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.tar.gz
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu22.04_arm64.tar.gz

        - name: js-interposer
          version_suffix: -ubuntu24.04
          platforms: linux/arm64
          source: /opt/selkies-js-interposer_${{ needs.get_semver.outputs.semver }}.tar.gz
          target: selkies-js-interposer_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}_ubuntu24.04_arm64.tar.gz

        - name: py-build
          source: /opt/pypi/dist/selkies_gstreamer-${{ needs.get_semver.outputs.semver }}-py3-none-any.whl
          target: selkies_gstreamer-${{ needs.get_semver.outputs.semver }}-py3-none-any.whl

        - name: gst-web
          source: /opt/gst-web.tar.gz
          target: selkies-gstreamer-web_${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}.tar.gz

    name: ${{ matrix.description }} release artifact extraction & upload
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: ${{ matrix.description }} release artifact extraction
      run: |
        docker container create --name=copy --platform="${{ matrix.platforms || 'linux/amd64' }}" "ghcr.io/${{ github.repository }}/${{ matrix.name }}:${{ github.event_name != 'pull_request' && github.ref_name || 'main' }}${{ matrix.version_suffix }}"
        TARGET_PATH="${{ env.TEMP_DIR }}/${{ matrix.target }}"
        docker container cp "copy:${{ matrix.source }}" "${TARGET_PATH}"
        if [ -d "${TARGET_PATH}" ]; then
          SOURCE_DIRNAME=$(echo "${{ matrix.source }}" | sed 's:.*/::')
          cd "${{ env.TEMP_DIR }}" && mv -f "${TARGET_PATH}" "${SOURCE_DIRNAME}"
          tar -czvf "temp.tar.gz" "${SOURCE_DIRNAME}" && rm -rf "${SOURCE_DIRNAME}" && mv -f "temp.tar.gz" "${TARGET_PATH}"
        fi
        docker container rm --force --volumes copy

    - name: ${{ matrix.description }} upload
      uses: svenstaro/upload-release-action@v2
      with:
        draft: true
        overwrite: true
        tag: ${{ github.ref }}
        file: ${{ env.TEMP_DIR }}/${{ matrix.target }}
