name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  get_semver:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.get.outputs.semver }}
    steps:
      - id: get
        env:
          RELEASE_VERSION: $GITHUB_REF_NAME
        run: echo ::set-output name=semver::${RELEASE_VERSION/v/}

  # Note: When modifying this job, copy modifications to all other workflows' image jobs.
  all_images:
    needs: get_semver
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: coturn
            source_directory: addons/coturn

          - name: coturn-web
            source_directory: addons/coturn-web

          - name: gst-py-example
            version_suffix: -ubuntu18.04
            build_args: PACKAGE_VERSION=${{ needs.get_semver.outputs.semver }};UBUNTU_RELEASE=18.04;GSTREAMER_BASE_IMAGE_RELEASE=$GITHUB_REF_NAME;PY_BUILD_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/py-build:$GITHUB_REF_NAME;WEB_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/gst-web:$GITHUB_REF_NAME
            dockerfile: Dockerfile.example
            source_directory: .

          - name: gst-py-example
            build_args: PACKAGE_VERSION=${{ needs.get_semver.outputs.semver }};UBUNTU_RELEASE=20.04;GSTREAMER_BASE_IMAGE_RELEASE=$GITHUB_REF_NAME;PY_BUILD_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/py-build:$GITHUB_REF_NAME;WEB_IMAGE=ghcr.io/selkies-project/selkies-gstreamer/gst-web:$GITHUB_REF_NAME
            dockerfile: Dockerfile.example
            source_directory: .

          - name: gst-web
            source_directory: addons/gst-web

          - name: gstreamer
            version_suffix: -ubuntu18.04
            build_args: BASE_IMAGE=ubuntu:18.04;
            source_directory: addons/gstreamer

          - name: gstreamer
            version_suffix: -ubuntu20.04
            build_args: BASE_IMAGE=ubuntu:20.04;
            source_directory: addons/gstreamer

          - name: infra-gcp-installer
            source_directory: infra/gce/installer-image

          - name: py-build
            build_args: PACKAGE_VERSION=0.0.0.dev0
            source_directory: .

    name: ${{ matrix.name }}${{ matrix.version_suffix }} image build & publish
    steps:
      - uses: actions/checkout@v2

      - name: Build & publish ${{ matrix.name }} image
        uses: ./.github/actions/build_and_publish_image
        with:
          github_personal_access_token: ${{ secrets.GITHUB_TOKEN }}
          github_username: $GITHUB_ACTOR
          image_source_directory: ${{ matrix.source_directory }}
          image_tag_1: ghcr.io/selkies-project/selkies-gstreamer/${{ matrix.name }}:$GITHUB_REF_NAME${{ matrix.version_suffix }}

  ###
  # Publish gstreamer Ubuntu 18.04 artifacts to GCS
  ###
  publish_gstreamer_gcs_ubuntu1804:
    runs-on: ubuntu-latest
    needs:
      - all_images
    outputs:
      asset_path: ${{ steps.extract_asset.outputs.asset_path }}
      asset_name: ${{ steps.extract_asset.outputs.asset_name }}
      asset_mimetype: ${{ steps.extract_asset.outputs.asset_mimetype }}
    steps:
      - name: Extract and Upload Asset to GCS
        id: extract_asset
        env:
          GCS_SA_KEY: ${{ secrets.GCP_ACTIONS_SA_KEY }}
          RELEASE_VERSION: $GITHUB_REF_NAME
        run: |
          # GHCR Login
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # GCS Login
          cat - > /tmp/sa_key.json <<EOF
          ${{ secrets.GCP_ACTIONS_SA_KEY }}
          EOF
          gcloud -q auth activate-service-account --key-file /tmp/sa_key.json

          # Docker create
          docker create --name copy ghcr.io/selkies-project/selkies-gstreamer/gstreamer:${RELEASE_VERSION}-ubuntu18.04

          # Docker copy and create tarball
          docker cp copy:/opt/selkies-gstreamer-latest.tgz /tmp/selkies-gstreamer-${RELEASE_VERSION}-ubuntu18.04.tgz

          # Docker rm
          docker rm copy

          # Copy to GCS
          gsutil cp /tmp/selkies-gstreamer-${RELEASE_VERSION}-ubuntu18.04.tgz gs://selkies-project-releases/selkies-gstreamer/${RELEASE_VERSION}/

          echo ::set-output name=asset_path::/tmp/selkies-gstreamer-${RELEASE_VERSION}-ubuntu18.04.tgz
          echo ::set-output name=asset_name::selkies-gstreamer-${RELEASE_VERSION}-ubuntu18.04.tgz
          echo ::set-output name=asset_mimetype::application/tar+gzip

      - name: Cache Asset
        id: cache_asset
        uses: actions/cache@v2
        with:
          path: ${{ steps.extract_asset.outputs.asset_path }}
          key: gstreamer-asset-ubuntu1804

  ###
  # Publish gstreamer Ubuntu 20.04 artifacts to GCS
  ###
  publish_gstreamer_gcs_ubuntu2004:
    runs-on: ubuntu-latest
    needs:
      - all_images
    outputs:
      asset_path: ${{ steps.extract_asset.outputs.asset_path }}
      asset_name: ${{ steps.extract_asset.outputs.asset_name }}
      asset_mimetype: ${{ steps.extract_asset.outputs.asset_mimetype }}
    steps:
      - name: Extract and Upload Asset to GCS
        id: extract_asset
        env:
          GCS_SA_KEY: ${{ secrets.GCP_ACTIONS_SA_KEY }}
          RELEASE_VERSION: $GITHUB_REF_NAME
        run: |
          # GHCR Login
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # GCS Login
          cat - > /tmp/sa_key.json <<EOF
          ${{ secrets.GCP_ACTIONS_SA_KEY }}
          EOF
          gcloud -q auth activate-service-account --key-file /tmp/sa_key.json

          # Docker create
          docker create --name copy ghcr.io/selkies-project/selkies-gstreamer/gstreamer:${RELEASE_VERSION}-ubuntu20.04

          # Docker copy and create tarball
          docker cp copy:/opt/selkies-gstreamer-latest.tgz /tmp/selkies-gstreamer-${RELEASE_VERSION}-ubuntu20.04.tgz

          # Docker rm
          docker rm copy

          # Copy to GCS
          gsutil cp /tmp/selkies-gstreamer-${RELEASE_VERSION}-ubuntu20.04.tgz gs://selkies-project-releases/selkies-gstreamer/${RELEASE_VERSION}/

          echo ::set-output name=asset_path::/tmp/selkies-gstreamer-${RELEASE_VERSION}-ubuntu20.04.tgz
          echo ::set-output name=asset_name::selkies-gstreamer-${RELEASE_VERSION}-ubuntu20.04.tgz
          echo ::set-output name=asset_mimetype::application/tar+gzip

      - name: Cache Asset
        id: cache_asset
        uses: actions/cache@v2
        with:
          path: ${{ steps.extract_asset.outputs.asset_path }}
          key: gstreamer-asset-ubuntu2004

  ###
  # Publish gst-py artifacts to GCS
  ###
  publish_gst_py_gcs:
    runs-on: ubuntu-latest
    needs:
      - all_images
    outputs:
      asset_path: ${{ steps.extract_asset.outputs.asset_path }}
      asset_name: ${{ steps.extract_asset.outputs.asset_name }}
      asset_mimetype: ${{ steps.extract_asset.outputs.asset_mimetype }}
    steps:
      - name: Extract and Upload Asset to GCS
        id: extract_asset
        env:
          GCS_SA_KEY: ${{ secrets.GCP_ACTIONS_SA_KEY }}
          PACKAGE_VERSION: ${{ needs.get_semver.outputs.semver }}
          PYPI_PACKAGE: selkies_gstreamer
          RELEASE_VERSION: $GITHUB_REF_NAME
        run: |
          # GHCR Login
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # GCS Login
          cat - > /tmp/sa_key.json <<EOF
          ${{ secrets.GCP_ACTIONS_SA_KEY }}
          EOF
          gcloud -q auth activate-service-account --key-file /tmp/sa_key.json

          # Docker create
          docker create --name copy ghcr.io/selkies-project/selkies-gstreamer/py-build:${RELEASE_VERSION}

          # Docker copy and create tarball
          docker cp copy:/opt/pypi/dist/${PYPI_PACKAGE}-${PACKAGE_VERSION}-py3-none-any.whl /tmp/${PYPI_PACKAGE}-${PACKAGE_VERSION}-py3-none-any.whl

          # Docker rm
          docker rm copy

          # Copy to GCS
          gsutil cp /tmp/${PYPI_PACKAGE}-${PACKAGE_VERSION}-py3-none-any.whl gs://selkies-project-releases/selkies-gstreamer/${RELEASE_VERSION}/

          echo ::set-output name=asset_path::/tmp/${PYPI_PACKAGE}-${PACKAGE_VERSION}-py3-none-any.whl
          echo ::set-output name=asset_name::${PYPI_PACKAGE}-${PACKAGE_VERSION}-py3-none-any.whl
          echo ::set-output name=asset_mimetype::application/x-pywheel+zip

      - name: Cache Asset
        id: cache_asset
        uses: actions/cache@v2
        with:
          path: ${{ steps.extract_asset.outputs.asset_path }}
          key: gst-py-asset

  ###
  # Publish gst-web artifacts to GCS
  ###
  publish_gst_web_gcs:
    runs-on: ubuntu-latest
    needs:
      - all_images
    outputs:
      asset_path: ${{ steps.extract_asset.outputs.asset_path }}
      asset_name: ${{ steps.extract_asset.outputs.asset_name }}
      asset_mimetype: ${{ steps.extract_asset.outputs.asset_mimetype }}
    steps:
      - name: Extract and Upload Asset to GCS
        id: extract_asset
        env:
          GCS_SA_KEY: ${{ secrets.GCP_ACTIONS_SA_KEY }}
          RELEASE_VERSION: $GITHUB_REF_NAME
        run: |
          # GHCR Login
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # GCS Login
          cat - > /tmp/sa_key.json <<EOF
          ${{ secrets.GCP_ACTIONS_SA_KEY }}
          EOF
          gcloud -q auth activate-service-account --key-file /tmp/sa_key.json

          # Docker create
          docker create --name copy ghcr.io/selkies-project/selkies-gstreamer/gst-web:${RELEASE_VERSION}

          # Docker copy and create tarball
          (cd /tmp && docker cp copy:/usr/share/nginx/html ./gst-web && tar zcvf /tmp/selkies-gstreamer-web-${RELEASE_VERSION}.tgz gst-web)

          # Docker rm
          docker rm copy

          # Copy to GCS
          gsutil cp /tmp/selkies-gstreamer-web-${RELEASE_VERSION}.tgz gs://selkies-project-releases/selkies-gstreamer/${RELEASE_VERSION}/

          echo ::set-output name=asset_path::/tmp/selkies-gstreamer-web-${RELEASE_VERSION}.tgz
          echo ::set-output name=asset_name::selkies-gstreamer-web-${RELEASE_VERSION}.tgz
          echo ::set-output name=asset_mimetype::application/tar+gzip

      - name: Cache Asset
        id: cache_asset
        uses: actions/cache@v2
        with:
          path: ${{ steps.extract_asset.outputs.asset_path }}
          key: gst-web-asset

  ###
  # Create Github Release
  ###
  create_release:
    runs-on: ubuntu-latest
    needs:
      - publish_gstreamer_gcs_ubuntu2004
      - publish_gstreamer_gcs_ubuntu1804
      - publish_gst_py_gcs
      - publish_gst_web_gcs
      - build_gst-py-example_ubuntu1804
      - build_gst-py-example_ubuntu2004
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Cache Asset, gstreamer
        id: gstreamer_cache_asset_ubuntu2004
        uses: actions/cache@v2
        with:
          path: ${{ needs.publish_gstreamer_gcs_ubuntu2004.outputs.asset_path }}
          key: gstreamer-asset-ubuntu2004
      - name: Cache Asset, gstreamer-ubuntu1804
        id: gstreamer_cache_asset_ubuntu1804
        uses: actions/cache@v2
        with:
          path: ${{ needs.publish_gstreamer_gcs_ubuntu1804.outputs.asset_path }}
          key: gstreamer-asset-ubuntu1804
      - name: Cache Asset, gst-py
        id: gst_py_cache_asset
        uses: actions/cache@v2
        with:
          path: ${{ needs.publish_gst_py_gcs.outputs.asset_path }}
          key: gst-py-asset
      - name: Cache Asset, gst-web
        id: gst_web_cache_asset
        uses: actions/cache@v2
        with:
          path: ${{ needs.publish_gst_web_gcs.outputs.asset_path }}
          key: gst-web-asset

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload GStreamer Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.publish_gstreamer_gcs_ubuntu2004.outputs.asset_path }}
          asset_name: ${{ needs.publish_gstreamer_gcs_ubuntu2004.outputs.asset_name }}
          asset_content_type: ${{ needs.publish_gstreamer_gcs_ubuntu2004.outputs.asset_mimetype }}

      - name: Upload GStreamer Ubuntu 18.04 Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.publish_gstreamer_gcs_ubuntu1804.outputs.asset_path }}
          asset_name: ${{ needs.publish_gstreamer_gcs_ubuntu1804.outputs.asset_name }}
          asset_content_type: ${{ needs.publish_gstreamer_gcs_ubuntu1804.outputs.asset_mimetype }}

      - name: Upload gst-py Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.publish_gst_py_gcs.outputs.asset_path }}
          asset_name: ${{ needs.publish_gst_py_gcs.outputs.asset_name }}
          asset_content_type: ${{ needs.publish_gst_py_gcs.outputs.asset_mimetype }}

      - name: Upload gst-web Asset to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.publish_gst_web_gcs.outputs.asset_path }}
          asset_name: ${{ needs.publish_gst_web_gcs.outputs.asset_name }}
          asset_content_type: ${{ needs.publish_gst_web_gcs.outputs.asset_mimetype }}
