kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: coturn

secretGenerator:
- name: turn-shared-secret
  files:
  - TURN_SHARED_SECRET
  - TURN_REALM

configMapGenerator:
  - name: coturn-web-config
    files:
    - MIG_DISCO_FILTER
    - MIG_DISCO_PROJECT_ID

resources:
  - namespace.yaml
  - coturn-discovery-service.yaml
  - coturn-gateway.yaml
  - coturn-web-rbac.yaml
  - coturn-web-deploy.yaml
  - coturn-web-service.yaml
  - coturn-web-virtualservice.yaml
